name=BraccioLib
version=1.0.0
author=Jakob Krakauer
sentence=Real-Time Motion Control library for the Arduino Tinkerkit Braccio Robot
paragraph=Provides high-level motion commands such as linear, circular movements and gripper control.
category=Robotics
architectures=*